Added slash commands (needs testing on docker)
atomheartother/A-I-kyan pull request #111
Opened 2022-03-04 23:54 UTC by leonardobagi

- Full support for slash commands, I guess
- Change `message` to `messageCreate` in `bot.ts`

The handler worked in my testing bot, but it needs to be tested within QTweet and Docker

2022-03-08 05:48 UTC, atomheartother requested changes

2022-03-08 05:48 UTC, atomheartother commented on src/shard/discord/loadSlashCommandFiles.ts
> +  const commandFiles = fs.readdirSync('../slashCommands', { withFileTypes: true }).filter((file) => file.name.endsWith('.ts'));
This is a huge no, find a better way to load slash command definitions

2022-03-08 05:48 UTC, atomheartother commented on package.json
> +    "discord.js": "github:ahnolds/discord.js#master",
This code clearly isn't up to date, rebase to `develop` and fix your conflicts please.

2022-03-08 05:48 UTC, atomheartother commented on src/shard/bot.ts
> +    .on('ready', handleReady.bind(null, getClient())) // also binded because i need the client
Can't you just get the client with `getClient` when you need it instead of binding it?

2022-03-08 05:48 UTC, atomheartother commented on src/shard/commands/tweet.ts
> +  screenNames.forEach((screenName: string) => postTimeline(qChannel, screenName, count, flags));
Did you actually change anything here? Please undo this formatting either way.

2022-03-08 05:48 UTC, atomheartother commented on src/shard/discord/discord.ts
> +    permissions.has(Permissions.FLAGS.ATTACH_FILES)
Undo this formatting as well.

2022-03-08 05:48 UTC, atomheartother commented on src/shard/discord/discordEvents.ts
> +      // Option with no equal
Same gerally in this file, i can't see what you changed.

2022-03-08 05:48 UTC, atomheartother commented on src/shard/commands/help.ts
>      embed(qChannel, { embed: helpMsg });
This won't send, please update to `develop`.

2022-03-08 05:48 UTC, atomheartother commented on src/shard/bot.ts
> +  log('⚙️ Creating Discord client...');
Idem, undo this formatting.

2022-03-08 05:48 UTC, atomheartother commented on src/shard/slashCommands/announce.ts
> +    },
I'm confused, where's the permission control? As far as I can see anyone can run any command with this code.

2022-03-08 13:32 UTC, leonardobagi commented on src/shard/slashCommands/announce.ts
> +    },
No such permission control in your `commands/announce.ts` as well, I took base on it. I will add it

2022-03-08 13:37 UTC, leonardobagi commented on src/shard/discord/loadSlashCommandFiles.ts
> +  const commandFiles = fs.readdirSync('../slashCommands', { withFileTypes: true }).filter((file) => file.name.endsWith('.ts'));
Well I don't think importing every single file manually and making an object with it's data is the best way either

2022-03-08 13:38 UTC, leonardobagi commented on package.json
> +    "discord.js": "github:ahnolds/discord.js#master",
I rebased to `liz/discord-update` as you told me to

2022-03-08 13:39 UTC, leonardobagi commented on src/shard/bot.ts
> +    .on('ready', handleReady.bind(null, getClient())) // also binded because i need the client
Not gonna lie that is actually very smart, I haven't thought of that. I am used to bind stuff

2022-03-08 13:41 UTC, leonardobagi commented on src/shard/commands/tweet.ts
> +  screenNames.forEach((screenName: string) => postTimeline(qChannel, screenName, count, flags));
I didn't even touched this file, I really don't know why it got reformatted

2022-03-08 13:43 UTC, leonardobagi commented on src/shard/commands/help.ts
>      embed(qChannel, { embed: helpMsg });
What do you mean "not send"?

2022-03-08 14:07 UTC, leonardobagi commented on src/shard/discord/discord.ts
> +    permissions.has(Permissions.FLAGS.ATTACH_FILES)
I am going to wrap all permissions in a single array

2022-03-08 14:28 UTC, leonardobagi commented on src/shard/slashCommands/announce.ts
> +    },
Added checks in all files.

2022-03-08 14:34 UTC, leonardobagi commented on src/shard/bot.ts
> +    .on('ready', handleReady.bind(null, getClient())) // also binded because i need the client
Done

2022-03-08 14:34 UTC, leonardobagi commented on src/shard/discord/discord.ts
> +    permissions.has(Permissions.FLAGS.ATTACH_FILES)
Removed formatting and put everything in an array

2022-03-08 14:35 UTC, leonardobagi commented on src/shard/discord/discordEvents.ts
> +      // Option with no equal
Removed as much formatting as I could and kept mostly my changes

2022-03-08 14:36 UTC, leonardobagi commented on src/shard/commands/tweet.ts
> +  screenNames.forEach((screenName: string) => postTimeline(qChannel, screenName, count, flags));
Removed formatting

2022-03-08 14:47 UTC, leonardobagi commented
Resolved conflicts

2022-03-12 15:25 UTC, atomheartother commented on src/shard/discord/loadSlashCommandFiles.ts
> +  const commandFiles = fs.readdirSync('../slashCommands', { withFileTypes: true }).filter((file) => file.name.endsWith('.ts'));
It's literally the same thing, without having to query the filesystem at runtime

2022-03-12 17:58 UTC, atomheartother commented on src/shard/discord/loadSlashCommandFiles.ts
> +  const commandFiles = fs.readdirSync('../slashCommands', { withFileTypes: true }).filter((file) => file.name.endsWith('.ts'));
Did it myself!

2022-03-12 17:59 UTC, atomheartother approved these changes

2022-03-13 18:29 UTC, leonardobagi reviewed
Also added `resolveJsonModule` to tsconfig,json

2022-03-13 21:42 UTC, merged